set(${CMAKE_PROJECT_NAME}_TEST FALSE)

if(NOT DEFINED ${TARGET_PLATFORM})
    if(EMSCRIPTEN)
        set(${CMAKE_PROJECT_NAME}_TEST TRUE)

        set(TARGET_PLATFORM "emscripten")
        list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__EMSCRIPTEN__=1")
        if(VR)
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
        endif()
    elseif(WIN32)
        set(${CMAKE_PROJECT_NAME}_TEST TRUE)

        if(ARCH_64)
            set(TARGET_PLATFORM "windows")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__WINDOWS64__=1")
            if(OCULUS)
                list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
            endif()
        else()
            set(TARGET_PLATFORM "windows")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__WINDOWS32__=1")
            if(OCULUS)
                list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
            endif()
        endif()
    elseif(APPLE)
        if(IOS)
            set(TARGET_PLATFORM "ios")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__IPHONEOS__=1")
            if(VR)
                list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
            endif()
        elseif(TVOS)
            set(TARGET_PLATFORM "appletvos")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__APPLETVOS__=1")
        else()
            set(${CMAKE_PROJECT_NAME}_TEST TRUE)

            set(TARGET_PLATFORM "macos")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__MACOS__=1")
            if(OCULUS)
                list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
            endif()
        endif()
    elseif(UNIX AND NOT APPLE AND NOT ANDROID)
        set(${CMAKE_PROJECT_NAME}_TEST TRUE)

        if(CMAKE_SYSTEM_NAME MATCHES ".*Linux")
            set(TARGET_PLATFORM "linux")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__LINUX__=1")
            if(OCULUS)
                list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__VR__=1")
            endif()
        elseif(UNIX)
            set(TARGET_PLATFORM "unix")
            list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__UNIX__=1")
        endif()
    elseif(ANDROID)
        set(${CMAKE_PROJECT_NAME}_TEST TRUE)
        set(TARGET_PLATFORM "android")
        list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS "__ANDROID__=1")
    endif()
endif()

set(PLATFORM_DIR "${CMAKE_CURRENT_SOURCE_DIR}/platform/${TARGET_PLATFORM}")
